import { GeneratedFile } from './codeGenerator';

interface GitHubPushParams {
  token: string;
  repoName: string;
  files: GeneratedFile[];
  description?: string;
  isPrivate?: boolean;
}

export async function pushToGitHub({
  token,
  repoName,
  files,
  description = 'Generated by metadata-driven app builder runtime',
  isPrivate = true,
}: GitHubPushParams): Promise<{ success: boolean; repoUrl?: string; error?: string }> {
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github.v3+json',
    'Content-Type': 'application/json',
    'User-Agent': 'metadata-runtime-exporter',
  };

  try {
    // 1. Get user login details to find the owner name
    const userRes = await fetch('https://api.github.com/user', { headers });
    if (!userRes.ok) {
      const errText = await userRes.text();
      return { success: false, error: `Invalid GitHub token: ${errText}` };
    }
    const userData = await userRes.json();
    const owner = userData.login;

    // 2. Check if repository already exists
    let repoRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}`, { headers });
    let isNewRepo = false;

    if (repoRes.status === 404) {
      // Repository doesn't exist, create it with auto_init to bootstrap the main branch with a commit
      isNewRepo = true;
      const createRes = await fetch('https://api.github.com/user/repos', {
        method: 'POST',
        headers,
        body: JSON.stringify({
          name: repoName,
          description,
          private: isPrivate,
          auto_init: true, // Creates README.md and commits it, establishing refs/heads/main
        }),
      });

      if (!createRes.ok) {
        const errText = await createRes.text();
        return { success: false, error: `Failed to create repository: ${errText}` };
      }
      repoRes = createRes;
    } else if (!repoRes.ok) {
      const errText = await repoRes.text();
      return { success: false, error: `Failed to query repository: ${errText}` };
    }

    const repoData = await repoRes.json();
    const repoUrl = repoData.html_url;

    // Wait a brief moment for GitHub to finish initializing if it's a brand new repo
    if (isNewRepo) {
      await new Promise((resolve) => setTimeout(resolve, 3000));
    }

    // 3. Get the reference of the main branch
    const refRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/ref/heads/main`, { headers });
    if (!refRes.ok) {
      const errText = await refRes.text();
      return { success: false, error: `Failed to fetch main branch ref: ${errText}` };
    }
    const refData = await refRes.json();
    const parentCommitSha = refData.object.sha;

    // 4. Create the git tree payload with all our files
    const treeItems = files.map((file) => ({
      path: file.path,
      mode: '100644', // normal file
      type: 'blob',
      content: file.content,
    }));

    const treeRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/trees`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        base_tree: parentCommitSha,
        tree: treeItems,
      }),
    });

    if (!treeRes.ok) {
      const errText = await treeRes.text();
      return { success: false, error: `Failed to create git tree structure: ${errText}` };
    }
    const treeData = await treeRes.json();
    const newTreeSha = treeData.sha;

    // 5. Create the git commit pointing to the new tree
    const commitRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/commits`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        message: 'Bootstrap codebase compiled from metadata runtime engine',
        tree: newTreeSha,
        parents: [parentCommitSha],
      }),
    });

    if (!commitRes.ok) {
      const errText = await commitRes.text();
      return { success: false, error: `Failed to create commit: ${errText}` };
    }
    const commitData = await commitRes.json();
    const newCommitSha = commitData.sha;

    // 6. Update the ref heads/main to point to the new commit
    const updateRefRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/refs/heads/main`, {
      method: 'PATCH',
      headers,
      body: JSON.stringify({
        sha: newCommitSha,
        force: true,
      }),
    });

    if (!updateRefRes.ok) {
      const errText = await updateRefRes.text();
      return { success: false, error: `Failed to update branch reference: ${errText}` };
    }

    return { success: true, repoUrl };
  } catch (err: any) {
    return { success: false, error: err.message || 'Unknown network error' };
  }
}
